---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # 1 hour

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install common packages
      apt:
        name:
          - curl
          - wget
          - git
          - vim
          - net-tools
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Configure firewall (example - allow SSH)
      ufw:
        rule: allow
        port: "22"  # SSH Port

    - name: Enable Firewall
      ufw:
        state: enabled
      ignore_errors: yes  # Allow if already enabled