apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1 # For production, consider more replicas
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: timescale/timescaledb:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: your_postgres_password  # Replace with a secure password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data #standard location for postgres databases
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc #Link to the persistence volume claim