apiVersion: v1
clusters:
- cluster:
    server: 192.168.1.170
  name: coin-beta
contexts:
- context:
    cluster: coin-beta
    user: stepan
  name: coin-beta
current-context: coin-beta
kind: Config
preferences: {}
users:
- name: stepan
  user:
    token: sksk
    