apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi... # Base64 encoded CA certificate
    server: https://your-kubernetes-api-server:6443 # **REPLACE** with API server address
  name: coin-beta # **REPLACE**

contexts:
- context:
    cluster: coin-beta # **REPLACE** Must match cluster name above
    user: stepan # **REPLACE** Must match user name below
  name: coin-beta # **REPLACE**

current-context: coin-beta # **REPLACE** One of the context name

users:
- name: stepan # **REPLACE**
  user:
    token: sksk # **REPLACE** Or use client-certificate/client-key