apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: mlflow #Needs to match namespace from above
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP #Expose internally within the Kubernetes cluster