apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce #Adjust accordingly
  resources:
    requests:
      storage: 10Gi #Size is just an example