apiVersion: v1
kind: Service
metadata:
  name: flyte-core
  namespace: flyte
spec:
  selector:
    app: flyte-core
  ports:
    - protocol: TCP
      port: 8080 #Update the port for Flyte Core
      targetPort: 8080 #Update the port for Flyte Core
  type: ClusterIP #Update Type if you are exposing externally